graph TD
A[Начало работы] --> B[Загрузка конфигурации]
B --> C{Проверка флага Enabled запускать задание}
C -- Yes --> D{Проверка флага Create_Backup_Rar создавать архив}
C -- No --> O[Завершение работы]
D -- Yes --> E[Запуск Create_Backup_Rar.ps1]
E --> F{Проверка статуса архивации}
F -- Success --> G{Проверка флага Copy-Robocopy создавать копию}
F -- Error --> K[Фиксирование ошибки]
D -- No --> G
G -- Yes --> H[Запуск Copy-Robocopy.ps1]
H --> I{Проверка статуса копирования}
I -- Success --> J{Проверка флага Remove-OldFiles удалять старые файлы}
I -- Error --> K
G -- No --> J
J -- Yes --> L[Запуск Remove-OldFiles.ps1]
L --> M{Проверка статуса очистки}
M -- Success --> N{Проверка флага Send-Mail отправлять сообщения}
M -- Error --> K
J -- No --> N
N -- Yes --> P[Запуск Send-Mail.ps1]
P --> O[Завершение работы]
N -- No --> O
K --> O
O --> A