jobs:
  JOB1:
    masks:
      - "*CTP*.*"
      - "ACQ_ADV_*.*"
      - "OAI_*.*"
      - "OAM_*.*"
      - "PART_CTL*.*"
      - "CTL*.*"
      - "PART_MTL*.*"
      - "*MTP*.*"
      - "OBR_*.*"
      - "OCI_*.*"
      - "OIA_*.*"
      - "OSM_*.*"
      - "CSJN_*.*"
      - "AFP20*.*"
      - "AFP_ACQ*.*"

  JOB2:
    masks:
      - "IBI_*.*"
      - "IIA_*.*"
